name: mall
app:
  env: dev
  name: go-mall
  log:
    path: "/tmp/appLog/go-mall.log"
    max_size: 100
    max_age: 60
database:
  master:
    type: mysql
    dsn: root:123456@tcp(localhost:3306)/go_mall?charset=utf8&parseTime=True&loc=Asia%2FShanghai
    maxopen: 100
    maxidle: 10
    maxlifetime: 300000000000 # 300s 内可复用
  slave:
    type: mysql
    dsn: root:123456@tcp(localhost:3306)/go_mall?charset=utf8&parseTime=True&loc=Asia%2FShanghai
    maxopen: 100
    maxidle: 10
    maxlifetime: 300000000000